name: this is first file
on:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main
  workflow_dispatch:

jobs:
  git_checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: first action
        run: echo " ths is firs github"
        shell: bash
